name: SecVersESQLC
version: '1.1'
main: org.secverse.secVersEssentialsXMySQLConnector.SecVersEssentialsXMySQLConnector
api-version: '1.21'
load: STARTUP
authors: [ Mia_conmeow ]
description: Bidirectional EssentialsX ⇆ MySQL synchronisation

commands:
  syncforce:
    description: Manually import/export Essentials data
    usage: /syncforce <import|export>
    permission: essentials.sync

permissions:
  essentials.sync:
    description: Allows manual import/export of Essentials data
    default: op
